ignore:
  - vulnerability: CVE-2026-12318
    package:
      name: libnss3
      type: deb
  - vulnerability: CVE-2026-23868
    package:
      name: libgif7
      type: deb
  - vulnerability: CVE-2026-41992
    package:
      name: gzip
      type: deb
  - vulnerability: CVE-2026-54369
    package:
      name: libacl1
      type: deb
  - vulnerability: CVE-2026-54370
    package:
      name: libacl1
      type: deb
  - vulnerability: CVE-2026-54371
    package:
      name: libattr1
      type: deb
  - vulnerability: CVE-2026-56361
    package:
      name: imagemagick
      type: deb
  - vulnerability: CVE-2026-56361
    package:
      name: imagemagick-7-common
      type: deb
  - vulnerability: CVE-2026-56361
    package:
      name: imagemagick-7.q16
      type: deb
  - vulnerability: CVE-2026-56361
    package:
      name: libmagickcore-7.q16-10
      type: deb
  - vulnerability: CVE-2026-56361
    package:
      name: libmagickwand-7.q16-10
      type: deb
  - vulnerability: CVE-2026-56367
    package:
      name: imagemagick
      type: deb
  - vulnerability: CVE-2026-56367
    package:
      name: imagemagick-7-common
      type: deb
  - vulnerability: CVE-2026-56367
    package:
      name: imagemagick-7.q16
      type: deb
  - vulnerability: CVE-2026-56367
    package:
      name: libmagickcore-7.q16-10
      type: deb
  - vulnerability: CVE-2026-56367
    package:
      name: libmagickwand-7.q16-10
      type: deb
  - vulnerability: CVE-2026-56368
    package:
      name: imagemagick
      type: deb
  - vulnerability: CVE-2026-56368
    package:
      name: imagemagick-7-common
      type: deb
  - vulnerability: CVE-2026-56368
    package:
      name: imagemagick-7.q16
      type: deb
  - vulnerability: CVE-2026-56368
    package:
      name: libmagickcore-7.q16-10
      type: deb
  - vulnerability: CVE-2026-56368
    package:
      name: libmagickwand-7.q16-10
      type: deb
  - vulnerability: CVE-2026-56370
    package:
      name: imagemagick
      type: deb
  - vulnerability: CVE-2026-56370
    package:
      name: imagemagick-7-common
      type: deb
  - vulnerability: CVE-2026-56370
    package:
      name: imagemagick-7.q16
      type: deb
  - vulnerability: CVE-2026-56370
    package:
      name: libmagickcore-7.q16-10
      type: deb
  - vulnerability: CVE-2026-56370
    package:
      name: libmagickwand-7.q16-10
      type: deb
  - vulnerability: CVE-2026-56378
    package:
      name: imagemagick
      type: deb
  - vulnerability: CVE-2026-56378
    package:
      name: imagemagick-7-common
      type: deb
  - vulnerability: CVE-2026-56378
    package:
      name: imagemagick-7.q16
      type: deb
  - vulnerability: CVE-2026-56378
    package:
      name: libmagickcore-7.q16-10
      type: deb
  - vulnerability: CVE-2026-56378
    package:
      name: libmagickwand-7.q16-10
      type: deb
  - vulnerability: CVE-2026-56379
    package:
      name: imagemagick
      type: deb
  - vulnerability: CVE-2026-56379
    package:
      name: imagemagick-7-common
      type: deb
  - vulnerability: CVE-2026-56379
    package:
      name: imagemagick-7.q16
      type: deb
  - vulnerability: CVE-2026-56379
    package:
      name: libmagickcore-7.q16-10
      type: deb
  - vulnerability: CVE-2026-56379
    package:
      name: libmagickwand-7.q16-10
      type: deb
  - vulnerability: CVE-2026-58010
    package:
      name: libglib2.0-0t64
      type: deb
  - vulnerability: CVE-2026-58011
    package:
      name: libglib2.0-0t64
      type: deb
  - vulnerability: CVE-2026-58012
    package:
      name: libglib2.0-0t64
      type: deb
  - vulnerability: CVE-2026-58013
    package:
      name: libglib2.0-0t64
      type: deb
  - vulnerability: CVE-2026-58014
    package:
      name: libglib2.0-0t64
      type: deb
  - vulnerability: CVE-2026-58015
    package:
      name: libglib2.0-0t64
      type: deb
  - vulnerability: CVE-2026-58016
    package:
      name: libglib2.0-0t64
      type: deb
  - vulnerability: CVE-2026-10536
    package:
      name: curl
      type: deb
  - vulnerability: CVE-2026-10536
    package:
      name: libcurl3t64-gnutls
      type: deb
  - vulnerability: CVE-2026-10536
    package:
      name: libcurl4t64
      type: deb
  - vulnerability: CVE-2026-11856
    package:
      name: curl
      type: deb
  - vulnerability: CVE-2026-11856
    package:
      name: libcurl3t64-gnutls
      type: deb
  - vulnerability: CVE-2026-11856
    package:
      name: libcurl4t64
      type: deb
  - vulnerability: CVE-2026-12064
    package:
      name: curl
      type: deb
  - vulnerability: CVE-2026-12064
    package:
      name: libcurl3t64-gnutls
      type: deb
  - vulnerability: CVE-2026-12064
    package:
      name: libcurl4t64
      type: deb
  - vulnerability: CVE-2026-58049
    package:
      name: libavcodec61
      type: deb
  - vulnerability: CVE-2026-58049
    package:
      name: libavformat61
      type: deb
  - vulnerability: CVE-2026-58049
    package:
      name: libavutil59
      type: deb
  - vulnerability: CVE-2026-58049
    package:
      name: libswresample5
      type: deb
  - vulnerability: CVE-2026-8286
    package:
      name: curl
      type: deb
  - vulnerability: CVE-2026-8286
    package:
      name: libcurl3t64-gnutls
      type: deb
  - vulnerability: CVE-2026-8286
    package:
      name: libcurl4t64
      type: deb
  - vulnerability: CVE-2026-8924
    package:
      name: curl
      type: deb
  - vulnerability: CVE-2026-8924
    package:
      name: libcurl3t64-gnutls
      type: deb
  - vulnerability: CVE-2026-8924
    package:
      name: libcurl4t64
      type: deb
  - vulnerability: CVE-2026-8926
    package:
      name: curl
      type: deb
  - vulnerability: CVE-2026-8926
    package:
      name: libcurl3t64-gnutls
      type: deb
  - vulnerability: CVE-2026-8926
    package:
      name: libcurl4t64
      type: deb
  - vulnerability: CVE-2026-8927
    package:
      name: curl
      type: deb
  - vulnerability: CVE-2026-8927
    package:
      name: libcurl3t64-gnutls
      type: deb
  - vulnerability: CVE-2026-8927
    package:
      name: libcurl4t64
      type: deb
  - vulnerability: CVE-2026-8932
    package:
      name: curl
      type: deb
  - vulnerability: CVE-2026-8932
    package:
      name: libcurl3t64-gnutls
      type: deb
  - vulnerability: CVE-2026-8932
    package:
      name: libcurl4t64
      type: deb
  - vulnerability: CVE-2026-9079
    package:
      name: curl
      type: deb
  - vulnerability: CVE-2026-9079
    package:
      name: libcurl3t64-gnutls
      type: deb
  - vulnerability: CVE-2026-9079
    package:
      name: libcurl4t64
      type: deb
  - vulnerability: CVE-2026-9080
    package:
      name: curl
      type: deb
  - vulnerability: CVE-2026-9080
    package:
      name: libcurl3t64-gnutls
      type: deb
  - vulnerability: CVE-2026-9080
    package:
      name: libcurl4t64
      type: deb
  - vulnerability: CVE-2026-9545
    package:
      name: curl
      type: deb
  - vulnerability: CVE-2026-9545
    package:
      name: libcurl3t64-gnutls
      type: deb
  - vulnerability: CVE-2026-9545
    package:
      name: libcurl4t64
      type: deb
  - vulnerability: CVE-2026-9547
    package:
      name: curl
      type: deb
  - vulnerability: CVE-2026-9547
    package:
      name: libcurl3t64-gnutls
      type: deb
  - vulnerability: CVE-2026-9547
    package:
      name: libcurl4t64
      type: deb
