ignore:
  - vulnerability: CVE-2026-56372
    package:
      name: imagemagick
      type: deb
  - vulnerability: CVE-2026-56372
    package:
      name: imagemagick-7-common
      type: deb
  - vulnerability: CVE-2026-56372
    package:
      name: imagemagick-7.q16
      type: deb
  - vulnerability: CVE-2026-56372
    package:
      name: libmagickcore-7.q16-10
      type: deb
  - vulnerability: CVE-2026-56372
    package:
      name: libmagickwand-7.q16-10
      type: deb
  - vulnerability: CVE-2026-61857
    package:
      name: imagemagick
      type: deb
  - vulnerability: CVE-2026-61857
    package:
      name: imagemagick-7-common
      type: deb
  - vulnerability: CVE-2026-61857
    package:
      name: imagemagick-7.q16
      type: deb
  - vulnerability: CVE-2026-61857
    package:
      name: libmagickcore-7.q16-10
      type: deb
  - vulnerability: CVE-2026-61857
    package:
      name: libmagickwand-7.q16-10
      type: deb
  - vulnerability: CVE-2026-61861
    package:
      name: imagemagick
      type: deb
  - vulnerability: CVE-2026-61861
    package:
      name: imagemagick-7-common
      type: deb
  - vulnerability: CVE-2026-61861
    package:
      name: imagemagick-7.q16
      type: deb
  - vulnerability: CVE-2026-61861
    package:
      name: libmagickcore-7.q16-10
      type: deb
  - vulnerability: CVE-2026-61861
    package:
      name: libmagickwand-7.q16-10
      type: deb
  - vulnerability: CVE-2026-61863
    package:
      name: imagemagick
      type: deb
  - vulnerability: CVE-2026-61863
    package:
      name: imagemagick-7-common
      type: deb
  - vulnerability: CVE-2026-61863
    package:
      name: imagemagick-7.q16
      type: deb
  - vulnerability: CVE-2026-61863
    package:
      name: libmagickcore-7.q16-10
      type: deb
  - vulnerability: CVE-2026-61863
    package:
      name: libmagickwand-7.q16-10
      type: deb
  - vulnerability: CVE-2026-61866
    package:
      name: imagemagick
      type: deb
  - vulnerability: CVE-2026-61866
    package:
      name: imagemagick-7-common
      type: deb
  - vulnerability: CVE-2026-61866
    package:
      name: imagemagick-7.q16
      type: deb
  - vulnerability: CVE-2026-61866
    package:
      name: libmagickcore-7.q16-10
      type: deb
  - vulnerability: CVE-2026-61866
    package:
      name: libmagickwand-7.q16-10
      type: deb
  - vulnerability: CVE-2026-61870
    package:
      name: imagemagick
      type: deb
  - vulnerability: CVE-2026-61870
    package:
      name: imagemagick-7-common
      type: deb
  - vulnerability: CVE-2026-61870
    package:
      name: imagemagick-7.q16
      type: deb
  - vulnerability: CVE-2026-61870
    package:
      name: libmagickcore-7.q16-10
      type: deb
  - vulnerability: CVE-2026-61870
    package:
      name: libmagickwand-7.q16-10
      type: deb
  - vulnerability: CVE-2025-59375
    package:
      name: libexpat1
      type: deb
  - vulnerability: CVE-2025-68431
    package:
      name: libheif-plugin-dav1d
      type: deb
  - vulnerability: CVE-2025-68431
    package:
      name: libheif-plugin-libde265
      type: deb
  - vulnerability: CVE-2025-68431
    package:
      name: libheif1
      type: deb
  - vulnerability: CVE-2025-69720
    package:
      name: libncurses6
      type: deb
  - vulnerability: CVE-2025-69720
    package:
      name: libncursesw6
      type: deb
  - vulnerability: CVE-2025-69720
    package:
      name: libtinfo6
      type: deb
  - vulnerability: CVE-2025-69720
    package:
      name: ncurses-base
      type: deb
  - vulnerability: CVE-2025-69720
    package:
      name: ncurses-bin
      type: deb
  - vulnerability: CVE-2026-0966
    package:
      name: libssh-4
      type: deb
  - vulnerability: CVE-2026-11822
    package:
      name: libsqlite3-0
      type: deb
  - vulnerability: CVE-2026-11824
    package:
      name: libsqlite3-0
      type: deb
  - vulnerability: CVE-2026-14164
    package:
      name: libarchive13t64
      type: deb
  - vulnerability: CVE-2026-20884
    package:
      name: libraw23t64
      type: deb
  - vulnerability: CVE-2026-20889
    package:
      name: libraw23t64
      type: deb
  - vulnerability: CVE-2026-21413
    package:
      name: libraw23t64
      type: deb
  - vulnerability: CVE-2026-24450
    package:
      name: libraw23t64
      type: deb
  - vulnerability: CVE-2026-24660
    package:
      name: libraw23t64
      type: deb
  - vulnerability: CVE-2026-24882
    package:
      name: dirmngr
      type: deb
  - vulnerability: CVE-2026-24882
    package:
      name: gnupg
      type: deb
  - vulnerability: CVE-2026-24882
    package:
      name: gnupg-l10n
      type: deb
  - vulnerability: CVE-2026-24882
    package:
      name: gpg
      type: deb
  - vulnerability: CVE-2026-24882
    package:
      name: gpg-agent
      type: deb
  - vulnerability: CVE-2026-24882
    package:
      name: gpgconf
      type: deb
  - vulnerability: CVE-2026-24882
    package:
      name: gpgsm
      type: deb
  - vulnerability: CVE-2026-25210
    package:
      name: libexpat1
      type: deb
  - vulnerability: CVE-2026-25835
    package:
      name: libmbedcrypto16
      type: deb
  - vulnerability: CVE-2026-34872
    package:
      name: libmbedcrypto16
      type: deb
  - vulnerability: CVE-2026-34873
    package:
      name: libmbedcrypto16
      type: deb
  - vulnerability: CVE-2026-34874
    package:
      name: libmbedcrypto16
      type: deb
  - vulnerability: CVE-2026-34875
    package:
      name: libmbedcrypto16
      type: deb
  - vulnerability: CVE-2026-34876
    package:
      name: libmbedcrypto16
      type: deb
  - vulnerability: CVE-2026-34990
    package:
      name: libcups2t64
      type: deb
  - vulnerability: CVE-2026-3731
    package:
      name: libssh-4
      type: deb
  - vulnerability: CVE-2026-41080
    package:
      name: libexpat1
      type: deb
  - vulnerability: CVE-2026-42496
    package:
      name: libperl5.40
      type: deb
  - vulnerability: CVE-2026-42496
    package:
      name: perl
      type: deb
  - vulnerability: CVE-2026-42496
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-42496
    package:
      name: perl-modules-5.40
      type: deb
  - vulnerability: CVE-2026-42497
    package:
      name: libperl5.40
      type: deb
  - vulnerability: CVE-2026-42497
    package:
      name: perl
      type: deb
  - vulnerability: CVE-2026-42497
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-42497
    package:
      name: perl-modules-5.40
      type: deb
  - vulnerability: CVE-2026-44168
    package:
      name: libmariadb3
      type: deb
  - vulnerability: CVE-2026-44168
    package:
      name: mariadb-client
      type: deb
  - vulnerability: CVE-2026-44168
    package:
      name: mariadb-client-core
      type: deb
  - vulnerability: CVE-2026-44168
    package:
      name: mariadb-common
      type: deb
  - vulnerability: CVE-2026-44171
    package:
      name: libmariadb3
      type: deb
  - vulnerability: CVE-2026-44171
    package:
      name: mariadb-client
      type: deb
  - vulnerability: CVE-2026-44171
    package:
      name: mariadb-client-core
      type: deb
  - vulnerability: CVE-2026-44171
    package:
      name: mariadb-common
      type: deb
  - vulnerability: CVE-2026-44172
    package:
      name: libmariadb3
      type: deb
  - vulnerability: CVE-2026-44172
    package:
      name: mariadb-client
      type: deb
  - vulnerability: CVE-2026-44172
    package:
      name: mariadb-client-core
      type: deb
  - vulnerability: CVE-2026-44172
    package:
      name: mariadb-common
      type: deb
  - vulnerability: CVE-2026-48163
    package:
      name: libmariadb3
      type: deb
  - vulnerability: CVE-2026-48163
    package:
      name: mariadb-client
      type: deb
  - vulnerability: CVE-2026-48163
    package:
      name: mariadb-client-core
      type: deb
  - vulnerability: CVE-2026-48163
    package:
      name: mariadb-common
      type: deb
  - vulnerability: CVE-2026-48165
    package:
      name: libmariadb3
      type: deb
  - vulnerability: CVE-2026-48165
    package:
      name: mariadb-client
      type: deb
  - vulnerability: CVE-2026-48165
    package:
      name: mariadb-client-core
      type: deb
  - vulnerability: CVE-2026-48165
    package:
      name: mariadb-common
      type: deb
  - vulnerability: CVE-2026-49261
    package:
      name: libmariadb3
      type: deb
  - vulnerability: CVE-2026-49261
    package:
      name: mariadb-client
      type: deb
  - vulnerability: CVE-2026-49261
    package:
      name: mariadb-client-core
      type: deb
  - vulnerability: CVE-2026-49261
    package:
      name: mariadb-common
      type: deb
  - vulnerability: CVE-2026-5435
    package:
      name: libc-bin
      type: deb
  - vulnerability: CVE-2026-5435
    package:
      name: libc6
      type: deb
  - vulnerability: CVE-2026-5450
    package:
      name: libc-bin
      type: deb
  - vulnerability: CVE-2026-5450
    package:
      name: libc6
      type: deb
  - vulnerability: CVE-2026-56374
    package:
      name: imagemagick
      type: deb
  - vulnerability: CVE-2026-56374
    package:
      name: imagemagick-7-common
      type: deb
  - vulnerability: CVE-2026-56374
    package:
      name: imagemagick-7.q16
      type: deb
  - vulnerability: CVE-2026-56374
    package:
      name: libmagickcore-7.q16-10
      type: deb
  - vulnerability: CVE-2026-56374
    package:
      name: libmagickwand-7.q16-10
      type: deb
  - vulnerability: CVE-2026-5928
    package:
      name: libc-bin
      type: deb
  - vulnerability: CVE-2026-5928
    package:
      name: libc6
      type: deb
  - vulnerability: CVE-2026-6653
    package:
      name: libxml2
      type: deb
  - vulnerability: CVE-2026-8376
    package:
      name: libperl5.40
      type: deb
  - vulnerability: CVE-2026-8376
    package:
      name: perl
      type: deb
  - vulnerability: CVE-2026-8376
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-8376
    package:
      name: perl-modules-5.40
      type: deb
  - vulnerability: CVE-2026-9538
    package:
      name: libperl5.40
      type: deb
  - vulnerability: CVE-2026-9538
    package:
      name: perl
      type: deb
  - vulnerability: CVE-2026-9538
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-9538
    package:
      name: perl-modules-5.40
      type: deb
  - vulnerability: CVE-2026-41992
    package:
      name: gzip
      type: deb
  - vulnerability: CVE-2026-54369
    package:
      name: libacl1
      type: deb
  - vulnerability: CVE-2026-54370
    package:
      name: libacl1
      type: deb
  - vulnerability: CVE-2026-58010
    package:
      name: libglib2.0-0t64
      type: deb
  - vulnerability: CVE-2026-58011
    package:
      name: libglib2.0-0t64
      type: deb
  - vulnerability: CVE-2026-58012
    package:
      name: libglib2.0-0t64
      type: deb
  - vulnerability: CVE-2026-58013
    package:
      name: libglib2.0-0t64
      type: deb
  - vulnerability: CVE-2026-58014
    package:
      name: libglib2.0-0t64
      type: deb
  - vulnerability: CVE-2026-58015
    package:
      name: libglib2.0-0t64
      type: deb
  - vulnerability: CVE-2026-58016
    package:
      name: libglib2.0-0t64
      type: deb
